services:
  mongo:
    image: mongo
    restart: unless-stopped
    env_file:
      - ./.env.prod
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data_prod:/data/db

  redis:
    image: redis
    restart: unless-stopped
    volumes:
      - redis_data_prod:/data
  app:
    image: todo-frontend
    restart: unless-stopped
    build:
      context: ./todo-frontend/
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=http://localhost:8080/api

  server:
    image: todo-backend
    restart: unless-stopped
    build:
      context: ./todo-backend/
      dockerfile: Dockerfile
    env_file:
      - ./.env.prod
    depends_on:
      - mongo
      - redis

  nginx:
    image: nginx:1.20.1
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server

volumes:
  mongo_data_prod:
  redis_data_prod:
